import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MuiProvider from "./MuiProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <MuiProvider>{children}</MuiProvider>
      </body>
    </html>
  );
}
