export default () => ({
  action: {},
  actionToggled: {},
  actionButton: {},
  row: {},
  rowSelected: {},
  rowItem: {},
  rowItemSelected: {},
  list: {},
  listItem: {},
  listItemSelected: {},
  parent: {},
  parentActive: {},
  parentCollapsed: {},

  lv1Row: {},
  lv1RowSelected: {},
  lv1RowItem: {},
  lv1RowItemSelected: {},
  lv1List: {},
  lv1Item: {},
  lv1ItemSelected: {},
  lv1Parent: {},
  lv1ParentActive: {},
  lv1ParentCollapsed: {},

  lv2Row: {},
  lv2RowSelected: {},
  lv2RowItem: {},
  lv2RowItemSelected: {},
  lv2List: {},
  lv2Item: {},
  lv2ItemSelected: {},
  lv2Parent: {},
  lv2ParentActive: {},
  lv2ParentCollapsed: {},

  lv3Row: {},
  lv3RowSelected: {},
  lv3RowItem: {},
  lv3RowItemSelected: {},
  lv3List: {},
  lv3Item: {},
  lv3ItemSelected: {},
  lv3Parent: {},
  lv3ParentActive: {},
  lv3ParentCollapsed: {},
});
