// AUTO-GENERATED by scripts/generate-demo-map.ts. Do not edit.
export type RegistryModuleLoader = () => Promise<Record<string, unknown>>;

const modules: Record<string, RegistryModuleLoader> = {
  'blocks/app-footer-01/app-footer-01': () =>
    import('@/registry/blocks/app-footer-01/app-footer-01'),
  'blocks/call-volume-trends/call-volume-trends': () =>
    import('@/registry/blocks/call-volume-trends/call-volume-trends'),
  'blocks/carousel-css-01/carousel-css-01': () =>
    import('@/registry/blocks/carousel-css-01/carousel-css-01'),
  'blocks/command-search-ui/command-search-ui': () =>
    import('@/registry/blocks/command-search-ui/command-search-ui'),
  'blocks/dashboard-sidebar/dashboard-sidebar': () =>
    import('@/registry/blocks/dashboard-sidebar/dashboard-sidebar'),
  'blocks/data-metrics/data-metrics': () =>
    import('@/registry/blocks/data-metrics/data-metrics'),
  'blocks/database-metrics-card/database-metrics-card': () =>
    import('@/registry/blocks/database-metrics-card/database-metrics-card'),
  'blocks/nav-menu-01/nav-menu-01': () =>
    import('@/registry/blocks/nav-menu-01/nav-menu-01'),
  'blocks/nav-menu-02/nav-menu-02': () =>
    import('@/registry/blocks/nav-menu-02/nav-menu-02'),
  'blocks/payment-history-chart/payment-history-chart': () =>
    import('@/registry/blocks/payment-history-chart/payment-history-chart'),
  'blocks/payment-overview-card/payment-overview-card': () =>
    import('@/registry/blocks/payment-overview-card/payment-overview-card'),
  'blocks/payroll-summary-card/payroll-summary-card': () =>
    import('@/registry/blocks/payroll-summary-card/payroll-summary-card'),
  'blocks/portfolio-value-chart/portfolio-value-chart': () =>
    import('@/registry/blocks/portfolio-value-chart/portfolio-value-chart'),
  'blocks/preference-settings/preference-settings': () =>
    import('@/registry/blocks/preference-settings/preference-settings'),
  'blocks/project-invite-modal/project-invite-modal': () =>
    import('@/registry/blocks/project-invite-modal/project-invite-modal'),
  'blocks/sidebar-navigation/sidebar-navigation': () =>
    import('@/registry/blocks/sidebar-navigation/sidebar-navigation'),
  'blocks/sla-performance-card/sla-performance-card': () =>
    import('@/registry/blocks/sla-performance-card/sla-performance-card'),
  'blocks/ticket-status-card/ticket-status-card': () =>
    import('@/registry/blocks/ticket-status-card/ticket-status-card'),
  'blocks/transaction-history-list/transaction-history-list': () =>
    import(
      '@/registry/blocks/transaction-history-list/transaction-history-list'
    ),
  'components/accordion-mui-treasury/accordion-mui-treasury': () =>
    import(
      '@/registry/components/accordion-mui-treasury/accordion-mui-treasury'
    ),
  'components/ai-actions/ai-actions': () =>
    import('@/registry/components/ai-actions/ai-actions'),
  'components/ai-actions/ai-actions.demo': () =>
    import('@/registry/components/ai-actions/ai-actions.demo'),
  'components/ai-artifact/ai-artifact': () =>
    import('@/registry/components/ai-artifact/ai-artifact'),
  'components/ai-artifact/ai-artifact.demo': () =>
    import('@/registry/components/ai-artifact/ai-artifact.demo'),
  'components/ai-branch/ai-branch': () =>
    import('@/registry/components/ai-branch/ai-branch'),
  'components/ai-branch/ai-branch.demo': () =>
    import('@/registry/components/ai-branch/ai-branch.demo'),
  'components/ai-chain-of-thought/ai-chain-of-thought': () =>
    import('@/registry/components/ai-chain-of-thought/ai-chain-of-thought'),
  'components/ai-chain-of-thought/ai-chain-of-thought.demo': () =>
    import(
      '@/registry/components/ai-chain-of-thought/ai-chain-of-thought.demo'
    ),
  'components/ai-code-block/ai-code-block': () =>
    import('@/registry/components/ai-code-block/ai-code-block'),
  'components/ai-code-block/ai-code-block.demo': () =>
    import('@/registry/components/ai-code-block/ai-code-block.demo'),
  'components/ai-context/ai-context': () =>
    import('@/registry/components/ai-context/ai-context'),
  'components/ai-context/ai-context.demo': () =>
    import('@/registry/components/ai-context/ai-context.demo'),
  'components/ai-conversation/ai-conversation': () =>
    import('@/registry/components/ai-conversation/ai-conversation'),
  'components/ai-conversation/ai-conversation.demo': () =>
    import('@/registry/components/ai-conversation/ai-conversation.demo'),
  'components/ai-image/ai-image': () =>
    import('@/registry/components/ai-image/ai-image'),
  'components/ai-image/ai-image.demo': () =>
    import('@/registry/components/ai-image/ai-image.demo'),
  'components/ai-inline-citation/ai-inline-citation': () =>
    import('@/registry/components/ai-inline-citation/ai-inline-citation'),
  'components/ai-inline-citation/ai-inline-citation.demo': () =>
    import('@/registry/components/ai-inline-citation/ai-inline-citation.demo'),
  'components/ai-loader/ai-loader': () =>
    import('@/registry/components/ai-loader/ai-loader'),
  'components/ai-loader/ai-loader.demo': () =>
    import('@/registry/components/ai-loader/ai-loader.demo'),
  'components/ai-message/ai-message': () =>
    import('@/registry/components/ai-message/ai-message'),
  'components/ai-message/ai-message.demo': () =>
    import('@/registry/components/ai-message/ai-message.demo'),
  'components/ai-open-in-chat/ai-open-in-chat': () =>
    import('@/registry/components/ai-open-in-chat/ai-open-in-chat'),
  'components/ai-open-in-chat/ai-open-in-chat.demo': () =>
    import('@/registry/components/ai-open-in-chat/ai-open-in-chat.demo'),
  'components/ai-prompt-input/ai-prompt-input': () =>
    import('@/registry/components/ai-prompt-input/ai-prompt-input'),
  'components/ai-prompt-input/ai-prompt-input.demo': () =>
    import('@/registry/components/ai-prompt-input/ai-prompt-input.demo'),
  'components/ai-reasoning/ai-reasoning': () =>
    import('@/registry/components/ai-reasoning/ai-reasoning'),
  'components/ai-reasoning/ai-reasoning.demo': () =>
    import('@/registry/components/ai-reasoning/ai-reasoning.demo'),
  'components/ai-response/ai-response': () =>
    import('@/registry/components/ai-response/ai-response'),
  'components/ai-response/ai-response.demo': () =>
    import('@/registry/components/ai-response/ai-response.demo'),
  'components/ai-sources/ai-sources': () =>
    import('@/registry/components/ai-sources/ai-sources'),
  'components/ai-sources/ai-sources.demo': () =>
    import('@/registry/components/ai-sources/ai-sources.demo'),
  'components/ai-suggestion/ai-suggestion': () =>
    import('@/registry/components/ai-suggestion/ai-suggestion'),
  'components/ai-suggestion/ai-suggestion.demo': () =>
    import('@/registry/components/ai-suggestion/ai-suggestion.demo'),
  'components/ai-task/ai-task': () =>
    import('@/registry/components/ai-task/ai-task'),
  'components/ai-task/ai-task.demo': () =>
    import('@/registry/components/ai-task/ai-task.demo'),
  'components/ai-tool/ai-tool': () =>
    import('@/registry/components/ai-tool/ai-tool'),
  'components/ai-tool/ai-tool.demo': () =>
    import('@/registry/components/ai-tool/ai-tool.demo'),
  'components/ai-web-preview/ai-web-preview': () =>
    import('@/registry/components/ai-web-preview/ai-web-preview'),
  'components/ai-web-preview/ai-web-preview.demo': () =>
    import('@/registry/components/ai-web-preview/ai-web-preview.demo'),
  'components/alert-mui-treasury/alert-mui-treasury': () =>
    import('@/registry/components/alert-mui-treasury/alert-mui-treasury'),
  'components/app-bar-mui-treasury/app-bar-mui-treasury': () =>
    import('@/registry/components/app-bar-mui-treasury/app-bar-mui-treasury'),
  'components/autocomplete-mui-treasury/autocomplete-mui-treasury': () =>
    import(
      '@/registry/components/autocomplete-mui-treasury/autocomplete-mui-treasury'
    ),
  'components/avatar-mui-treasury/avatar-mui-treasury': () =>
    import('@/registry/components/avatar-mui-treasury/avatar-mui-treasury'),
  'components/badge-mui-treasury/badge-mui-treasury': () =>
    import('@/registry/components/badge-mui-treasury/badge-mui-treasury'),
  'components/breadcrumbs-mui-treasury/breadcrumbs-mui-treasury': () =>
    import(
      '@/registry/components/breadcrumbs-mui-treasury/breadcrumbs-mui-treasury'
    ),
  'components/button-group-mui-treasury/button-group-mui-treasury': () =>
    import(
      '@/registry/components/button-group-mui-treasury/button-group-mui-treasury'
    ),
  'components/button-mui-treasury/button-mui-treasury': () =>
    import('@/registry/components/button-mui-treasury/button-mui-treasury'),
  'components/card-action-01/card-action-01': () =>
    import('@/registry/components/card-action-01/card-action-01'),
  'components/card-action-02/card-action-02': () =>
    import('@/registry/components/card-action-02/card-action-02'),
  'components/card-blog/card-blog': () =>
    import('@/registry/components/card-blog/card-blog'),
  'components/card-engagement/card-engagement': () =>
    import('@/registry/components/card-engagement/card-engagement'),
  'components/card-galaxy/card-galaxy': () =>
    import('@/registry/components/card-galaxy/card-galaxy'),
  'components/card-highlight/card-highlight': () =>
    import('@/registry/components/card-highlight/card-highlight'),
  'components/card-kanban/card-kanban': () =>
    import('@/registry/components/card-kanban/card-kanban'),
  'components/card-music/card-music': () =>
    import('@/registry/components/card-music/card-music'),
  'components/card-news/card-news': () =>
    import('@/registry/components/card-news/card-news'),
  'components/card-news2/card-news2': () =>
    import('@/registry/components/card-news2/card-news2'),
  'components/card-news3/card-news3': () =>
    import('@/registry/components/card-news3/card-news3'),
  'components/card-offer/card-offer': () =>
    import('@/registry/components/card-offer/card-offer'),
  'components/card-post/card-post': () =>
    import('@/registry/components/card-post/card-post'),
  'components/card-preview-01/card-preview-01': () =>
    import('@/registry/components/card-preview-01/card-preview-01'),
  'components/card-profile/card-profile': () =>
    import('@/registry/components/card-profile/card-profile'),
  'components/card-project/card-project': () =>
    import('@/registry/components/card-project/card-project'),
  'components/card-review/card-review': () =>
    import('@/registry/components/card-review/card-review'),
  'components/card-review2/card-review2': () =>
    import('@/registry/components/card-review2/card-review2'),
  'components/card-reward/card-reward': () =>
    import('@/registry/components/card-reward/card-reward'),
  'components/card-social/card-social': () =>
    import('@/registry/components/card-social/card-social'),
  'components/card-solid-game/card-solid-game': () =>
    import('@/registry/components/card-solid-game/card-solid-game'),
  'components/card-sysi/card-sysi': () =>
    import('@/registry/components/card-sysi/card-sysi'),
  'components/card-tag/card-tag': () =>
    import('@/registry/components/card-tag/card-tag'),
  'components/card-team/card-team': () =>
    import('@/registry/components/card-team/card-team'),
  'components/card-tutor/card-tutor': () =>
    import('@/registry/components/card-tutor/card-tutor'),
  'components/checkbox-mui-treasury/checkbox-mui-treasury': () =>
    import('@/registry/components/checkbox-mui-treasury/checkbox-mui-treasury'),
  'components/chip-mui-treasury/chip-mui-treasury': () =>
    import('@/registry/components/chip-mui-treasury/chip-mui-treasury'),
  'components/collapsible/demos/collapsible-icon.demo': () =>
    import('@/registry/components/collapsible/demos/collapsible-icon.demo'),
  'components/collapsible/demos/collapsible.demo': () =>
    import('@/registry/components/collapsible/demos/collapsible.demo'),
  'components/color-picker-field/color-picker-field': () =>
    import('@/registry/components/color-picker-field/color-picker-field'),
  'components/color-picker-field/color-picker-field.demo': () =>
    import('@/registry/components/color-picker-field/color-picker-field.demo'),
  'components/color-scheme-select-basic/color-scheme-select-basic': () =>
    import(
      '@/registry/components/color-scheme-select-basic/color-scheme-select-basic'
    ),
  'components/color-scheme-select-icon/color-scheme-select-icon': () =>
    import(
      '@/registry/components/color-scheme-select-icon/color-scheme-select-icon'
    ),
  'components/color-scheme-select-minimal/color-scheme-select-minimal': () =>
    import(
      '@/registry/components/color-scheme-select-minimal/color-scheme-select-minimal'
    ),
  'components/color-scheme-tabs-basic/color-scheme-tabs-basic': () =>
    import(
      '@/registry/components/color-scheme-tabs-basic/color-scheme-tabs-basic'
    ),
  'components/customer-metrics-card/customer-metrics-card': () =>
    import('@/registry/components/customer-metrics-card/customer-metrics-card'),
  'components/dialog-mui-treasury/dialog-mui-treasury': () =>
    import('@/registry/components/dialog-mui-treasury/dialog-mui-treasury'),
  'components/dropzone-01/dropzone-01': () =>
    import('@/registry/components/dropzone-01/dropzone-01'),
  'components/dropzone-01/dropzone-01.demo': () =>
    import('@/registry/components/dropzone-01/dropzone-01.demo'),
  'components/file-upload-field/file-upload-field': () =>
    import('@/registry/components/file-upload-field/file-upload-field'),
  'components/file-upload-field/file-upload-field.demo': () =>
    import('@/registry/components/file-upload-field/file-upload-field.demo'),
  'components/info-apex/info-apex': () =>
    import('@/registry/components/info-apex/info-apex'),
  'components/info-basic/info-basic.demo': () =>
    import('@/registry/components/info-basic/info-basic.demo'),
  'components/info-beats/info-beats': () =>
    import('@/registry/components/info-beats/info-beats'),
  'components/info-blog/info-blog': () =>
    import('@/registry/components/info-blog/info-blog'),
  'components/info-chatz/info-chatz': () =>
    import('@/registry/components/info-chatz/info-chatz'),
  'components/info-n01/info-n01': () =>
    import('@/registry/components/info-n01/info-n01'),
  'components/info-n02/info-n02': () =>
    import('@/registry/components/info-n02/info-n02'),
  'components/info-n03/info-n03': () =>
    import('@/registry/components/info-n03/info-n03'),
  'components/info-n04/info-n04': () =>
    import('@/registry/components/info-n04/info-n04'),
  'components/keycap-01/keycap-01': () =>
    import('@/registry/components/keycap-01/keycap-01'),
  'components/keycap-01/keycap-01.demo': () =>
    import('@/registry/components/keycap-01/keycap-01.demo'),
  'components/list-item-01/list-item-01': () =>
    import('@/registry/components/list-item-01/list-item-01'),
  'components/list-item-02/list-item-02': () =>
    import('@/registry/components/list-item-02/list-item-02'),
  'components/list-mui-treasury/list-mui-treasury': () =>
    import('@/registry/components/list-mui-treasury/list-mui-treasury'),
  'components/login-form-split/login-form-split': () =>
    import('@/registry/components/login-form-split/login-form-split'),
  'components/login-form/login-form': () =>
    import('@/registry/components/login-form/login-form'),
  'components/members-metric/members-metric': () =>
    import('@/registry/components/members-metric/members-metric'),
  'components/menu-mui-treasury/menu-mui-treasury': () =>
    import('@/registry/components/menu-mui-treasury/menu-mui-treasury'),
  'components/menubar-01/menubar-01': () =>
    import('@/registry/components/menubar-01/menubar-01'),
  'components/meter-01/meter-01': () =>
    import('@/registry/components/meter-01/meter-01'),
  'components/meter-01/meter-01.demo': () =>
    import('@/registry/components/meter-01/meter-01.demo'),
  'components/number-field-01/number-field-01': () =>
    import('@/registry/components/number-field-01/number-field-01'),
  'components/number-field-02/number-field-02': () =>
    import('@/registry/components/number-field-02/number-field-02'),
  'components/number-input/number-input': () =>
    import('@/registry/components/number-input/number-input'),
  'components/number-input/number-input.demo': () =>
    import('@/registry/components/number-input/number-input.demo'),
  'components/pagination-mui-treasury/pagination-mui-treasury': () =>
    import(
      '@/registry/components/pagination-mui-treasury/pagination-mui-treasury'
    ),
  'components/product-card/product-card': () =>
    import('@/registry/components/product-card/product-card'),
  'components/product-card2/product-card2': () =>
    import('@/registry/components/product-card2/product-card2'),
  'components/progress-mui-treasury/progress-mui-treasury': () =>
    import('@/registry/components/progress-mui-treasury/progress-mui-treasury'),
  'components/radio-card-01/radio-card-01': () =>
    import('@/registry/components/radio-card-01/radio-card-01'),
  'components/radio-color-01/radio-color-01': () =>
    import('@/registry/components/radio-color-01/radio-color-01'),
  'components/radio-mui-treasury/radio-mui-treasury': () =>
    import('@/registry/components/radio-mui-treasury/radio-mui-treasury'),
  'components/radio-segment-01/radio-segment-01': () =>
    import('@/registry/components/radio-segment-01/radio-segment-01'),
  'components/rating-mui-treasury/rating-mui-treasury': () =>
    import('@/registry/components/rating-mui-treasury/rating-mui-treasury'),
  'components/select-inset-01/select-inset-01': () =>
    import('@/registry/components/select-inset-01/select-inset-01'),
  'components/select-inset-01/select-inset-01.demo': () =>
    import('@/registry/components/select-inset-01/select-inset-01.demo'),
  'components/select-mui-treasury/select-mui-treasury': () =>
    import('@/registry/components/select-mui-treasury/select-mui-treasury'),
  'components/sidebar/demos/popup-menu.demo': () =>
    import('@/registry/components/sidebar/demos/popup-menu.demo'),
  'components/sidebar/demos/sidebar-group.demo': () =>
    import('@/registry/components/sidebar/demos/sidebar-group.demo'),
  'components/sidebar/demos/sidebar-menus.demo': () =>
    import('@/registry/components/sidebar/demos/sidebar-menus.demo'),
  'components/sidebar/demos/sidebar-text.demo': () =>
    import('@/registry/components/sidebar/demos/sidebar-text.demo'),
  'components/sidebar/demos/sidebar-tooltip.demo': () =>
    import('@/registry/components/sidebar/demos/sidebar-tooltip.demo'),
  'components/sidebar/sidebar.demo': () =>
    import('@/registry/components/sidebar/sidebar.demo'),
  'components/slider-01/slider-01': () =>
    import('@/registry/components/slider-01/slider-01'),
  'components/slider-01/slider-01.demo': () =>
    import('@/registry/components/slider-01/slider-01.demo'),
  'components/slider-mui-treasury/slider-mui-treasury': () =>
    import('@/registry/components/slider-mui-treasury/slider-mui-treasury'),
  'components/snackbar-mui-treasury/snackbar-mui-treasury': () =>
    import('@/registry/components/snackbar-mui-treasury/snackbar-mui-treasury'),
  'components/sonner/sonner': () =>
    import('@/registry/components/sonner/sonner'),
  'components/sonner/sonner.demo': () =>
    import('@/registry/components/sonner/sonner.demo'),
  'components/sonner2/sonner2': () =>
    import('@/registry/components/sonner2/sonner2'),
  'components/sonner2/sonner2.demo': () =>
    import('@/registry/components/sonner2/sonner2.demo'),
  'components/space-login/space-login': () =>
    import('@/registry/components/space-login/space-login'),
  'components/stepper-mui-treasury/stepper-mui-treasury': () =>
    import('@/registry/components/stepper-mui-treasury/stepper-mui-treasury'),
  'components/switch-mui-treasury/switch-mui-treasury': () =>
    import('@/registry/components/switch-mui-treasury/switch-mui-treasury'),
  'components/table-mui-treasury/table-mui-treasury': () =>
    import('@/registry/components/table-mui-treasury/table-mui-treasury'),
  'components/tabs-01/tabs-01': () =>
    import('@/registry/components/tabs-01/tabs-01'),
  'components/tabs-02/tabs-02': () =>
    import('@/registry/components/tabs-02/tabs-02'),
  'components/tabs-apple/tabs-apple': () =>
    import('@/registry/components/tabs-apple/tabs-apple'),
  'components/tabs-chip-01/tabs-chip-01': () =>
    import('@/registry/components/tabs-chip-01/tabs-chip-01'),
  'components/tabs-chrome/tabs-chrome': () =>
    import('@/registry/components/tabs-chrome/tabs-chrome'),
  'components/tabs-contained/tabs-contained': () =>
    import('@/registry/components/tabs-contained/tabs-contained'),
  'components/tabs-elevated/tabs-elevated': () =>
    import('@/registry/components/tabs-elevated/tabs-elevated'),
  'components/tabs-firebase/tabs-firebase': () =>
    import('@/registry/components/tabs-firebase/tabs-firebase'),
  'components/tabs-inside-triangle/tabs-inside-triangle': () =>
    import('@/registry/components/tabs-inside-triangle/tabs-inside-triangle'),
  'components/tabs-instagram/tabs-instagram': () =>
    import('@/registry/components/tabs-instagram/tabs-instagram'),
  'components/tabs-mui-treasury/tabs-mui-treasury': () =>
    import('@/registry/components/tabs-mui-treasury/tabs-mui-treasury'),
  'components/tabs-pill/tabs-pill': () =>
    import('@/registry/components/tabs-pill/tabs-pill'),
  'components/tabs-plain/tabs-plain': () =>
    import('@/registry/components/tabs-plain/tabs-plain'),
  'components/tabs-serrated/tabs-serrated': () =>
    import('@/registry/components/tabs-serrated/tabs-serrated'),
  'components/tabs-twitter/tabs-twitter': () =>
    import('@/registry/components/tabs-twitter/tabs-twitter'),
  'components/text-field-mui-treasury/text-field-mui-treasury': () =>
    import(
      '@/registry/components/text-field-mui-treasury/text-field-mui-treasury'
    ),
  'components/toggle-button-mui-treasury/toggle-button-mui-treasury': () =>
    import(
      '@/registry/components/toggle-button-mui-treasury/toggle-button-mui-treasury'
    ),
  'components/tooltip-mui-treasury/tooltip-mui-treasury': () =>
    import('@/registry/components/tooltip-mui-treasury/tooltip-mui-treasury'),
  'components/typography-mui-treasury/typography-mui-treasury': () =>
    import(
      '@/registry/components/typography-mui-treasury/typography-mui-treasury'
    ),
  'firebase/firebase-analyze-image/firebase-analyze-image': () =>
    import('@/registry/firebase/firebase-analyze-image/firebase-analyze-image'),
  'firebase/firebase-chat-transport/firebase-chat-transport': () =>
    import(
      '@/registry/firebase/firebase-chat-transport/firebase-chat-transport'
    ),
  'firebase/firebase-chat-transport/firebase-chat-transport.demo': () =>
    import(
      '@/registry/firebase/firebase-chat-transport/firebase-chat-transport.demo'
    ),
  'firebase/firebase-generate-text/firebase-generate-text': () =>
    import('@/registry/firebase/firebase-generate-text/firebase-generate-text'),
  'firebase/firebase-google-search/firebase-google-search': () =>
    import('@/registry/firebase/firebase-google-search/firebase-google-search'),
  'firebase/firebase-image-generation/firebase-image-generation': () =>
    import(
      '@/registry/firebase/firebase-image-generation/firebase-image-generation'
    ),
  'firebase/firebase-story-telling/firebase-story-telling': () =>
    import('@/registry/firebase/firebase-story-telling/firebase-story-telling'),
  'firebase/firebase-thinking-model/firebase-thinking-model': () =>
    import(
      '@/registry/firebase/firebase-thinking-model/firebase-thinking-model'
    ),
  'firebase/firebase-tool-calling/firebase-tool-calling': () =>
    import('@/registry/firebase/firebase-tool-calling/firebase-tool-calling'),
  'layout/app-analytics/app-analytics': () =>
    import('@/registry/layout/app-analytics/app-analytics'),
  'layout/app-messenger/app-messenger': () =>
    import('@/registry/layout/app-messenger/app-messenger'),
  'layout/app-shopping-cart/app-shopping-cart': () =>
    import('@/registry/layout/app-shopping-cart/app-shopping-cart'),
  'layout/layout-core/layout-core.demo': () =>
    import('@/registry/layout/layout-core/layout-core.demo'),
  'layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-auto-collapse.demo':
    () =>
      import(
        '@/registry/layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-auto-collapse.demo'
      ),
  'layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-collapse.demo':
    () =>
      import(
        '@/registry/layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-collapse.demo'
      ),
  'layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-drawer-without-overlay.demo':
    () =>
      import(
        '@/registry/layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-drawer-without-overlay.demo'
      ),
  'layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-drawer.demo': () =>
    import(
      '@/registry/layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-drawer.demo'
    ),
  'layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-hover-uncollapse.demo':
    () =>
      import(
        '@/registry/layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-hover-uncollapse.demo'
      ),
  'layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-responsive.demo':
    () =>
      import(
        '@/registry/layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-responsive.demo'
      ),
  'layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-right.demo': () =>
    import(
      '@/registry/layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-right.demo'
    ),
  'layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-visibility.demo':
    () =>
      import(
        '@/registry/layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-visibility.demo'
      ),
  'layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-width.demo': () =>
    import(
      '@/registry/layout/layout-docs-edge-sidebar/demos/layout-edge-sidebar-width.demo'
    ),
  'layout/layout-docs-footer/demos/layout-footer-inset-avoiding.demo': () =>
    import(
      '@/registry/layout/layout-docs-footer/demos/layout-footer-inset-avoiding.demo'
    ),
  'layout/layout-docs-header/demos/layout-header-clip.demo': () =>
    import(
      '@/registry/layout/layout-docs-header/demos/layout-header-clip.demo'
    ),
  'layout/layout-docs-header/demos/layout-header-height.demo': () =>
    import(
      '@/registry/layout/layout-docs-header/demos/layout-header-height.demo'
    ),
  'layout/layout-docs-inset-sidebar/demos/layout-inset-sidebar-absolute.demo':
    () =>
      import(
        '@/registry/layout/layout-docs-inset-sidebar/demos/layout-inset-sidebar-absolute.demo'
      ),
  'layout/layout-docs-inset-sidebar/demos/layout-inset-sidebar-sticky.demo':
    () =>
      import(
        '@/registry/layout/layout-docs-inset-sidebar/demos/layout-inset-sidebar-sticky.demo'
      ),
  'layout/layout-docs-inset-sidebar/demos/layout-inset-sidebar-width.demo':
    () =>
      import(
        '@/registry/layout/layout-docs-inset-sidebar/demos/layout-inset-sidebar-width.demo'
      ),
  'layout/layout-docs-root/demos/layout-root-disable-transition.demo': () =>
    import(
      '@/registry/layout/layout-docs-root/demos/layout-root-disable-transition.demo'
    ),
  'layout/layout-docs-root/demos/layout-root-height.demo': () =>
    import('@/registry/layout/layout-docs-root/demos/layout-root-height.demo'),
  'layout/layout-docs-root/demos/layout-root-standalone.demo': () =>
    import(
      '@/registry/layout/layout-docs-root/demos/layout-root-standalone.demo'
    ),
};

export function getModuleLoader(key: string): RegistryModuleLoader | null {
  return modules[key] ?? null;
}
