#!/usr/bin/env node

import * as fs from 'fs';
import * as path from 'path';
import * as prettier from 'prettier';

import { getRegistryItems } from '../lib/registry';

const OUTPUT = path.join(process.cwd(), 'lib', 'registry-demos.generated.ts');

const REGISTRY_DIR = path.join(process.cwd(), 'registry');

function stripExt(p: string): string {
  return p.replace(/\.tsx?$/, '');
}

function fileExists(relPathNoExt: string): boolean {
  return (
    fs.existsSync(path.join(REGISTRY_DIR, `${relPathNoExt}.tsx`)) ||
    fs.existsSync(path.join(REGISTRY_DIR, `${relPathNoExt}.ts`))
  );
}

function collectKeys(): string[] {
  const items = getRegistryItems();
  const keys = new Set<string>();
  for (const item of items) {
    if (item.path && /\.tsx?$/.test(item.path)) {
      const key = stripExt(item.path);
      if (fileExists(key)) keys.add(key);
    }
    for (const demo of item.demoFiles ?? []) {
      if (demo.path && /\.tsx?$/.test(demo.path)) {
        const key = stripExt(demo.path);
        if (fileExists(key)) keys.add(key);
      }
    }
  }
  return Array.from(keys).sort();
}

function render(keys: string[]): string {
  const entries = keys
    .map(
      (key) =>
        `  ${JSON.stringify(key)}: () => import(${JSON.stringify(`@/registry/${key}`)}),`,
    )
    .join('\n');

  return `// AUTO-GENERATED by scripts/generate-demo-map.ts. Do not edit.
export type RegistryModuleLoader = () => Promise<Record<string, unknown>>;

const modules: Record<string, RegistryModuleLoader> = {
${entries}
};

export function getModuleLoader(key: string): RegistryModuleLoader | null {
  return modules[key] ?? null;
}
`;
}

async function main() {
  const keys = collectKeys();
  const content = render(keys);
  const config = await prettier.resolveConfig(OUTPUT);
  const formatted = await prettier.format(content, {
    ...config,
    filepath: OUTPUT,
  });
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, formatted);
  console.log(
    `[generate-demo-map] wrote ${keys.length} entries → ${path.relative(process.cwd(), OUTPUT)}`,
  );
}

main();
