export const layoutClasses = {
  Root: "Root",
  Header: "Header",
  Content: "Content",
  Footer: "Footer",
  EdgeSidebar: "EdgeSidebar",
  EdgeSidebarContent: "EdgeSidebarContent",
  EdgeSidebarCollapser: "EdgeSidebar-collapser",
  EdgeDrawerTrigger: "EdgeDrawerTrigger",
  EdgeDrawerClose: "EdgeDrawerClose",
  EdgeDrawerOpenVisible: "EdgeDrawerOpen-visible",
  EdgeDrawerClosedVisible: "EdgeDrawerClosed-visible",
  EdgeCollapsedVisible: "EdgeCollapsedVisible",
  EdgeUncollapsedVisible: "EdgeUncollapsedVisible",
  EdgeSidebarRight: "EdgeSidebar-R",
  EdgeSidebarRightCollapser: "EdgeSidebar-R-collapser",
  EdgeDrawerTriggerRight: "EdgeDrawerTrigger-R",
  DrawerWithoutOverlay: "EdgeDrawer-withoutOverlay",
  InsetSidebar: "InsetSidebar",
  InsetContent: "InsetContent",
  InsetAvoidingView: "InsetAvoidingView",
  SidebarRail: "SidebarRail",
};
